name: Build and Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: discovairegistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image to ACR
        run: |
          docker build -t discovairegistry.azurecr.io/discovai_app:latest .  --platform=linux/amd64 --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}
          docker push discovairegistry.azurecr.io/discovai_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "DiscovAi"
          slot-name: "production"
          images: "discovairegistry.azurecr.io/discovai_app:latest"
